sfg:
  brewery:
    api_host: http://localhost:8080
  maxtotalconnections: 100
  defaultmaxtotalconnections: 20
  connectionrequesttimeout: 3000
  sockettimeout: 3000

logging:
  level:
    org:
      apache:
        http: debug
